import Nav from "@/components/Nav/nav.component"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <Nav />
      <body className='bg-gray-950 text-white'>{children}</body>
    </html>
  )
}
