import RTKStoreProvider from "@/components/RTKStoreProvider/rtk-store-provider.component";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="text-black">
        <RTKStoreProvider>
        {children}
        </RTKStoreProvider>
      </body>
    </html>
  );
}
